# .test/singularity/sra_reads/config/config.yaml

# Path to your SAMPLE SHEET which keeps track of your biological replicates
samples: .test/singularity/sra_reads/config/samples.tsv

# Path to your sequencing UNIT SHEET which keeps track of your technical
# replicates (e.g. sequencer lanes or resequencing of the same biological
# sample)
units: .test/singularity/sra_reads/config/units.tsv

ref:
  # GenBank or RefSeq accession number for the genome of the species of
  # interest (or closest related species if no reference genome exists)
  # Find the accession number here:
  #   https://www.ncbi.nlm.nih.gov/datasets/genome/
  # TODO: Workflow is only currently validated to work on RefSeq genomes
  ncbi_genome_accession: GCF_016699485.2 # Gallus gallus