# .test/sra_reads/config/config.yaml
# Configuration for testing with yeast RNA-Seq data from BioProject PRJNA1242481

# Path to your SAMPLE SHEET which keeps track of your biological replicates
samples: ".test/sra_reads/config_yeast/samples.tsv"

# Path to your sequencing UNIT SHEET which keeps track of your technical
# replicates (e.g. sequencer lanes or resequencing of the same biological
# sample)
units: ".test/sra_reads/config_yeast/units.tsv"
